from dataclasses import dataclass
from datetime import date


@dataclass(frozen=True)
class IndexDefinition:
    symbol: str
    name: str
    provider: str
    benchmark: str
    inception_date: date
    source_url: str
    holdings: tuple[dict[str, object], ...]


XLG_SOURCE = "https://www.invesco.com/us/en/financial-products/etfs/invesco-sp-500-top-50-etf.html"
SPY_SOURCE = "https://www.ssga.com/us/en/intermediary/etfs/state-street-spdr-sp-500-etf-trust-spy"
TOPT_SOURCE = "https://www.ishares.com/us/products/339779/ishares-top-20-us-stocks-etf"
QTOP_SOURCE = "https://www.ishares.com/us/products/339775/ishares-nasdaq-top-30-stocks-etf"


INDEX_DEFINITIONS: dict[str, IndexDefinition] = {
    "XLG": IndexDefinition(
        symbol="XLG",
        name="Invesco S&P 500 Top 50 ETF",
        provider="Invesco",
        benchmark="S&P 500 Top 50 Index",
        inception_date=date(2005, 5, 4),
        source_url=XLG_SOURCE,
        holdings=(
            {"symbol": "NVDA", "name": "NVIDIA Corp", "sector": "Information Technology", "weight": 0.1260},
            {"symbol": "AAPL", "name": "Apple Inc", "sector": "Information Technology", "weight": 0.1120},
            {"symbol": "MSFT", "name": "Microsoft Corp", "sector": "Information Technology", "weight": 0.0820},
            {"symbol": "AMZN", "name": "Amazon.com Inc", "sector": "Consumer Discretionary", "weight": 0.0610},
            {"symbol": "GOOGL", "name": "Alphabet Inc Class A", "sector": "Communication Services", "weight": 0.0490},
            {"symbol": "AVGO", "name": "Broadcom Inc", "sector": "Information Technology", "weight": 0.0440},
            {"symbol": "GOOG", "name": "Alphabet Inc Class C", "sector": "Communication Services", "weight": 0.0400},
            {"symbol": "META", "name": "Meta Platforms Inc", "sector": "Communication Services", "weight": 0.0370},
            {"symbol": "TSLA", "name": "Tesla Inc", "sector": "Consumer Discretionary", "weight": 0.0310},
            {"symbol": "BRK.B", "name": "Berkshire Hathaway Inc", "sector": "Financials", "weight": 0.0270},
            {"symbol": "JPM", "name": "JPMorgan Chase & Co", "sector": "Financials", "weight": 0.0240},
            {"symbol": "XOM", "name": "Exxon Mobil Corp", "sector": "Energy", "weight": 0.0210},
            {"symbol": "LLY", "name": "Eli Lilly and Co", "sector": "Health Care", "weight": 0.0210},
            {"symbol": "JNJ", "name": "Johnson & Johnson", "sector": "Health Care", "weight": 0.0180},
            {"symbol": "WMT", "name": "Walmart Inc", "sector": "Consumer Staples", "weight": 0.0170},
            {"symbol": "V", "name": "Visa Inc", "sector": "Financials", "weight": 0.0160},
            {"symbol": "MA", "name": "Mastercard Inc", "sector": "Financials", "weight": 0.0130},
            {"symbol": "COST", "name": "Costco Wholesale Corp", "sector": "Consumer Staples", "weight": 0.0120},
            {"symbol": "ABBV", "name": "AbbVie Inc", "sector": "Health Care", "weight": 0.0110},
            {"symbol": "HD", "name": "Home Depot Inc", "sector": "Consumer Discretionary", "weight": 0.0110},
            {"symbol": "PG", "name": "Procter & Gamble Co", "sector": "Consumer Staples", "weight": 0.0100},
            {"symbol": "NFLX", "name": "Netflix Inc", "sector": "Communication Services", "weight": 0.0100},
            {"symbol": "ORCL", "name": "Oracle Corp", "sector": "Information Technology", "weight": 0.0095},
            {"symbol": "KO", "name": "Coca-Cola Co", "sector": "Consumer Staples", "weight": 0.0090},
            {"symbol": "BAC", "name": "Bank of America Corp", "sector": "Financials", "weight": 0.0088},
            {"symbol": "CRM", "name": "Salesforce Inc", "sector": "Information Technology", "weight": 0.0085},
            {"symbol": "MRK", "name": "Merck & Co Inc", "sector": "Health Care", "weight": 0.0082},
            {"symbol": "AMD", "name": "Advanced Micro Devices Inc", "sector": "Information Technology", "weight": 0.0080},
            {"symbol": "CVX", "name": "Chevron Corp", "sector": "Energy", "weight": 0.0078},
            {"symbol": "CSCO", "name": "Cisco Systems Inc", "sector": "Information Technology", "weight": 0.0075},
            {"symbol": "PEP", "name": "PepsiCo Inc", "sector": "Consumer Staples", "weight": 0.0072},
            {"symbol": "WFC", "name": "Wells Fargo & Co", "sector": "Financials", "weight": 0.0070},
            {"symbol": "ACN", "name": "Accenture PLC", "sector": "Information Technology", "weight": 0.0068},
            {"symbol": "MCD", "name": "McDonald's Corp", "sector": "Consumer Discretionary", "weight": 0.0066},
            {"symbol": "LIN", "name": "Linde PLC", "sector": "Materials", "weight": 0.0064},
            {"symbol": "DIS", "name": "Walt Disney Co", "sector": "Communication Services", "weight": 0.0062},
            {"symbol": "TMO", "name": "Thermo Fisher Scientific Inc", "sector": "Health Care", "weight": 0.0060},
            {"symbol": "ABT", "name": "Abbott Laboratories", "sector": "Health Care", "weight": 0.0058},
            {"symbol": "INTU", "name": "Intuit Inc", "sector": "Information Technology", "weight": 0.0056},
            {"symbol": "IBM", "name": "International Business Machines Corp", "sector": "Information Technology", "weight": 0.0054},
            {"symbol": "GE", "name": "GE Aerospace", "sector": "Industrials", "weight": 0.0052},
            {"symbol": "AMGN", "name": "Amgen Inc", "sector": "Health Care", "weight": 0.0050},
            {"symbol": "CAT", "name": "Caterpillar Inc", "sector": "Industrials", "weight": 0.0048},
            {"symbol": "QCOM", "name": "Qualcomm Inc", "sector": "Information Technology", "weight": 0.0046},
            {"symbol": "NOW", "name": "ServiceNow Inc", "sector": "Information Technology", "weight": 0.0044},
            {"symbol": "TXN", "name": "Texas Instruments Inc", "sector": "Information Technology", "weight": 0.0042},
            {"symbol": "PM", "name": "Philip Morris International Inc", "sector": "Consumer Staples", "weight": 0.0040},
            {"symbol": "AMAT", "name": "Applied Materials Inc", "sector": "Information Technology", "weight": 0.0038},
            {"symbol": "SPGI", "name": "S&P Global Inc", "sector": "Financials", "weight": 0.0036},
            {"symbol": "UBER", "name": "Uber Technologies Inc", "sector": "Industrials", "weight": 0.0034},
        ),
    ),
    "SPY": IndexDefinition(
        symbol="SPY",
        name="SPDR S&P 500 ETF Trust",
        provider="State Street Global Advisors",
        benchmark="S&P 500 Index",
        inception_date=date(1993, 1, 22),
        source_url=SPY_SOURCE,
        holdings=(
            {"symbol": "NVDA", "name": "NVIDIA Corp", "sector": "Information Technology", "weight": 0.0800},
            {"symbol": "AAPL", "name": "Apple Inc", "sector": "Information Technology", "weight": 0.0700},
            {"symbol": "MSFT", "name": "Microsoft Corp", "sector": "Information Technology", "weight": 0.0600},
            {"symbol": "AMZN", "name": "Amazon.com Inc", "sector": "Consumer Discretionary", "weight": 0.0400},
            {"symbol": "GOOGL", "name": "Alphabet Inc Class A", "sector": "Communication Services", "weight": 0.0300},
            {"symbol": "AVGO", "name": "Broadcom Inc", "sector": "Information Technology", "weight": 0.0300},
            {"symbol": "META", "name": "Meta Platforms Inc", "sector": "Communication Services", "weight": 0.0300},
            {"symbol": "GOOG", "name": "Alphabet Inc Class C", "sector": "Communication Services", "weight": 0.0250},
            {"symbol": "TSLA", "name": "Tesla Inc", "sector": "Consumer Discretionary", "weight": 0.0220},
            {"symbol": "BRK.B", "name": "Berkshire Hathaway Inc", "sector": "Financials", "weight": 0.0190},
            {"symbol": "JPM", "name": "JPMorgan Chase & Co", "sector": "Financials", "weight": 0.0170},
            {"symbol": "WMT", "name": "Walmart Inc", "sector": "Consumer Staples", "weight": 0.0160},
            {"symbol": "LLY", "name": "Eli Lilly and Co", "sector": "Health Care", "weight": 0.0150},
            {"symbol": "V", "name": "Visa Inc", "sector": "Financials", "weight": 0.0140},
            {"symbol": "ORCL", "name": "Oracle Corp", "sector": "Information Technology", "weight": 0.0130},
            {"symbol": "XOM", "name": "Exxon Mobil Corp", "sector": "Energy", "weight": 0.0120},
            {"symbol": "MA", "name": "Mastercard Inc", "sector": "Financials", "weight": 0.0120},
            {"symbol": "NFLX", "name": "Netflix Inc", "sector": "Communication Services", "weight": 0.0110},
            {"symbol": "COST", "name": "Costco Wholesale Corp", "sector": "Consumer Staples", "weight": 0.0105},
            {"symbol": "JNJ", "name": "Johnson & Johnson", "sector": "Health Care", "weight": 0.0100},
            {"symbol": "HD", "name": "Home Depot Inc", "sector": "Consumer Discretionary", "weight": 0.0095},
            {"symbol": "PG", "name": "Procter & Gamble Co", "sector": "Consumer Staples", "weight": 0.0090},
            {"symbol": "ABBV", "name": "AbbVie Inc", "sector": "Health Care", "weight": 0.0090},
            {"symbol": "BAC", "name": "Bank of America Corp", "sector": "Financials", "weight": 0.0085},
            {"symbol": "UNH", "name": "UnitedHealth Group Inc", "sector": "Health Care", "weight": 0.0080},
            {"symbol": "KO", "name": "Coca-Cola Co", "sector": "Consumer Staples", "weight": 0.0078},
            {"symbol": "GE", "name": "GE Aerospace", "sector": "Industrials", "weight": 0.0075},
            {"symbol": "CRM", "name": "Salesforce Inc", "sector": "Information Technology", "weight": 0.0075},
            {"symbol": "CSCO", "name": "Cisco Systems Inc", "sector": "Information Technology", "weight": 0.0070},
            {"symbol": "CVX", "name": "Chevron Corp", "sector": "Energy", "weight": 0.0068},
            {"symbol": "WFC", "name": "Wells Fargo & Co", "sector": "Financials", "weight": 0.0067},
            {"symbol": "IBM", "name": "International Business Machines Corp", "sector": "Information Technology", "weight": 0.0065},
            {"symbol": "ABT", "name": "Abbott Laboratories", "sector": "Health Care", "weight": 0.0063},
            {"symbol": "MRK", "name": "Merck & Co Inc", "sector": "Health Care", "weight": 0.0062},
            {"symbol": "LIN", "name": "Linde PLC", "sector": "Materials", "weight": 0.0060},
            {"symbol": "MCD", "name": "McDonald's Corp", "sector": "Consumer Discretionary", "weight": 0.0058},
            {"symbol": "AMD", "name": "Advanced Micro Devices Inc", "sector": "Information Technology", "weight": 0.0056},
            {"symbol": "ACN", "name": "Accenture PLC", "sector": "Information Technology", "weight": 0.0055},
            {"symbol": "PM", "name": "Philip Morris International Inc", "sector": "Consumer Staples", "weight": 0.0054},
            {"symbol": "INTU", "name": "Intuit Inc", "sector": "Information Technology", "weight": 0.0052},
            {"symbol": "ISRG", "name": "Intuitive Surgical Inc", "sector": "Health Care", "weight": 0.0051},
            {"symbol": "MS", "name": "Morgan Stanley", "sector": "Financials", "weight": 0.0050},
            {"symbol": "GS", "name": "Goldman Sachs Group Inc", "sector": "Financials", "weight": 0.0049},
            {"symbol": "DIS", "name": "Walt Disney Co", "sector": "Communication Services", "weight": 0.0048},
            {"symbol": "RTX", "name": "RTX Corp", "sector": "Industrials", "weight": 0.0047},
            {"symbol": "TMO", "name": "Thermo Fisher Scientific Inc", "sector": "Health Care", "weight": 0.0046},
            {"symbol": "PEP", "name": "PepsiCo Inc", "sector": "Consumer Staples", "weight": 0.0045},
            {"symbol": "CAT", "name": "Caterpillar Inc", "sector": "Industrials", "weight": 0.0044},
            {"symbol": "AXP", "name": "American Express Co", "sector": "Financials", "weight": 0.0043},
            {"symbol": "QCOM", "name": "Qualcomm Inc", "sector": "Information Technology", "weight": 0.0042},
            {"symbol": "NOW", "name": "ServiceNow Inc", "sector": "Information Technology", "weight": 0.0041},
            {"symbol": "TXN", "name": "Texas Instruments Inc", "sector": "Information Technology", "weight": 0.0040},
            {"symbol": "BKNG", "name": "Booking Holdings Inc", "sector": "Consumer Discretionary", "weight": 0.0039},
            {"symbol": "VZ", "name": "Verizon Communications Inc", "sector": "Communication Services", "weight": 0.0038},
            {"symbol": "AMGN", "name": "Amgen Inc", "sector": "Health Care", "weight": 0.0037},
            {"symbol": "UBER", "name": "Uber Technologies Inc", "sector": "Industrials", "weight": 0.0036},
            {"symbol": "LOW", "name": "Lowe's Cos Inc", "sector": "Consumer Discretionary", "weight": 0.0035},
            {"symbol": "SPGI", "name": "S&P Global Inc", "sector": "Financials", "weight": 0.0035},
            {"symbol": "BSX", "name": "Boston Scientific Corp", "sector": "Health Care", "weight": 0.0034},
            {"symbol": "SCHW", "name": "Charles Schwab Corp", "sector": "Financials", "weight": 0.0033},
            {"symbol": "PGR", "name": "Progressive Corp", "sector": "Financials", "weight": 0.0032},
            {"symbol": "HON", "name": "Honeywell International Inc", "sector": "Industrials", "weight": 0.0031},
            {"symbol": "NEE", "name": "NextEra Energy Inc", "sector": "Utilities", "weight": 0.0030},
            {"symbol": "BLK", "name": "BlackRock Inc", "sector": "Financials", "weight": 0.0029},
            {"symbol": "TJX", "name": "TJX Cos Inc", "sector": "Consumer Discretionary", "weight": 0.0028},
            {"symbol": "C", "name": "Citigroup Inc", "sector": "Financials", "weight": 0.0028},
            {"symbol": "COP", "name": "ConocoPhillips", "sector": "Energy", "weight": 0.0027},
            {"symbol": "DHR", "name": "Danaher Corp", "sector": "Health Care", "weight": 0.0027},
            {"symbol": "GILD", "name": "Gilead Sciences Inc", "sector": "Health Care", "weight": 0.0026},
            {"symbol": "ADP", "name": "Automatic Data Processing Inc", "sector": "Industrials", "weight": 0.0026},
            {"symbol": "SYK", "name": "Stryker Corp", "sector": "Health Care", "weight": 0.0025},
            {"symbol": "BA", "name": "Boeing Co", "sector": "Industrials", "weight": 0.0025},
            {"symbol": "DE", "name": "Deere & Co", "sector": "Industrials", "weight": 0.0024},
            {"symbol": "AMAT", "name": "Applied Materials Inc", "sector": "Information Technology", "weight": 0.0024},
            {"symbol": "MDT", "name": "Medtronic PLC", "sector": "Health Care", "weight": 0.0023},
            {"symbol": "LMT", "name": "Lockheed Martin Corp", "sector": "Industrials", "weight": 0.0023},
            {"symbol": "PANW", "name": "Palo Alto Networks Inc", "sector": "Information Technology", "weight": 0.0022},
            {"symbol": "MMC", "name": "Marsh & McLennan Cos Inc", "sector": "Financials", "weight": 0.0022},
            {"symbol": "CB", "name": "Chubb Ltd", "sector": "Financials", "weight": 0.0021},
            {"symbol": "FI", "name": "Fiserv Inc", "sector": "Financials", "weight": 0.0021},
            {"symbol": "ETN", "name": "Eaton Corp PLC", "sector": "Industrials", "weight": 0.0020},
            {"symbol": "UPS", "name": "United Parcel Service Inc", "sector": "Industrials", "weight": 0.0020},
            {"symbol": "BMY", "name": "Bristol-Myers Squibb Co", "sector": "Health Care", "weight": 0.0019},
            {"symbol": "SBUX", "name": "Starbucks Corp", "sector": "Consumer Discretionary", "weight": 0.0019},
            {"symbol": "ADI", "name": "Analog Devices Inc", "sector": "Information Technology", "weight": 0.0018},
            {"symbol": "KLAC", "name": "KLA Corp", "sector": "Information Technology", "weight": 0.0018},
            {"symbol": "MU", "name": "Micron Technology Inc", "sector": "Information Technology", "weight": 0.0017},
            {"symbol": "PLD", "name": "Prologis Inc", "sector": "Real Estate", "weight": 0.0017},
            {"symbol": "LRCX", "name": "Lam Research Corp", "sector": "Information Technology", "weight": 0.0016},
            {"symbol": "MDLZ", "name": "Mondelez International Inc", "sector": "Consumer Staples", "weight": 0.0016},
            {"symbol": "SO", "name": "Southern Co", "sector": "Utilities", "weight": 0.0015},
            {"symbol": "EQIX", "name": "Equinix Inc", "sector": "Real Estate", "weight": 0.0015},
            {"symbol": "SHW", "name": "Sherwin-Williams Co", "sector": "Materials", "weight": 0.0014},
            {"symbol": "CVS", "name": "CVS Health Corp", "sector": "Health Care", "weight": 0.0014},
            {"symbol": "ELV", "name": "Elevance Health Inc", "sector": "Health Care", "weight": 0.0013},
            {"symbol": "MO", "name": "Altria Group Inc", "sector": "Consumer Staples", "weight": 0.0013},
            {"symbol": "ICE", "name": "Intercontinental Exchange Inc", "sector": "Financials", "weight": 0.0012},
            {"symbol": "WM", "name": "Waste Management Inc", "sector": "Industrials", "weight": 0.0012},
            {"symbol": "CME", "name": "CME Group Inc", "sector": "Financials", "weight": 0.0011},
            {"symbol": "CL", "name": "Colgate-Palmolive Co", "sector": "Consumer Staples", "weight": 0.0011},
            {"symbol": "APH", "name": "Amphenol Corp", "sector": "Information Technology", "weight": 0.0010},
            {"symbol": "DUK", "name": "Duke Energy Corp", "sector": "Utilities", "weight": 0.0010},
        ),
    ),
    "TOPT": IndexDefinition(
        symbol="TOPT",
        name="iShares Top 20 U.S. Stocks ETF",
        provider="iShares",
        benchmark="S&P 500 Top 20 Select Index",
        inception_date=date(2024, 10, 23),
        source_url=TOPT_SOURCE,
        holdings=(
            {"symbol": "NVDA", "name": "NVIDIA Corp", "sector": "Information Technology", "weight": 0.1645},
            {"symbol": "AAPL", "name": "Apple Inc", "sector": "Information Technology", "weight": 0.1361},
            {"symbol": "GOOGL", "name": "Alphabet Inc Class A", "sector": "Communication Services", "weight": 0.0669},
            {"symbol": "MSFT", "name": "Microsoft Corp", "sector": "Information Technology", "weight": 0.0587},
            {"symbol": "GOOG", "name": "Alphabet Inc Class C", "sector": "Communication Services", "weight": 0.0534},
            {"symbol": "AMZN", "name": "Amazon.com Inc", "sector": "Consumer Discretionary", "weight": 0.0504},
            {"symbol": "AVGO", "name": "Broadcom Inc", "sector": "Information Technology", "weight": 0.0496},
            {"symbol": "META", "name": "Meta Platforms Inc", "sector": "Communication Services", "weight": 0.0433},
            {"symbol": "BRK.B", "name": "Berkshire Hathaway Inc", "sector": "Financials", "weight": 0.0432},
            {"symbol": "JPM", "name": "JPMorgan Chase & Co", "sector": "Financials", "weight": 0.0415},
            {"symbol": "TSLA", "name": "Tesla Inc", "sector": "Consumer Discretionary", "weight": 0.0386},
            {"symbol": "LLY", "name": "Eli Lilly and Co", "sector": "Health Care", "weight": 0.0362},
            {"symbol": "XOM", "name": "Exxon Mobil Corp", "sector": "Energy", "weight": 0.0313},
            {"symbol": "JNJ", "name": "Johnson & Johnson", "sector": "Health Care", "weight": 0.0281},
            {"symbol": "WMT", "name": "Walmart Inc", "sector": "Consumer Staples", "weight": 0.0268},
            {"symbol": "V", "name": "Visa Inc", "sector": "Financials", "weight": 0.0255},
            {"symbol": "MU", "name": "Micron Technology Inc", "sector": "Information Technology", "weight": 0.0235},
            {"symbol": "NFLX", "name": "Netflix Inc", "sector": "Communication Services", "weight": 0.0214},
            {"symbol": "COST", "name": "Costco Wholesale Corp", "sector": "Consumer Staples", "weight": 0.0213},
            {"symbol": "MA", "name": "Mastercard Inc", "sector": "Financials", "weight": 0.0203},
            {"symbol": "ABBV", "name": "AbbVie Inc", "sector": "Health Care", "weight": 0.0179},
        ),
    ),
    "QTOP": IndexDefinition(
        symbol="QTOP",
        name="iShares Nasdaq Top 30 Stocks ETF",
        provider="iShares",
        benchmark="Nasdaq-100 Top 30 Index",
        inception_date=date(2024, 10, 23),
        source_url=QTOP_SOURCE,
        holdings=(
            {"symbol": "NVDA", "name": "NVIDIA Corp", "sector": "Information Technology", "weight": 0.1214},
            {"symbol": "AAPL", "name": "Apple Inc", "sector": "Information Technology", "weight": 0.0906},
            {"symbol": "MSFT", "name": "Microsoft Corp", "sector": "Information Technology", "weight": 0.0727},
            {"symbol": "AMZN", "name": "Amazon.com Inc", "sector": "Consumer Discretionary", "weight": 0.0646},
            {"symbol": "GOOGL", "name": "Alphabet Inc Class A", "sector": "Communication Services", "weight": 0.0470},
            {"symbol": "AVGO", "name": "Broadcom Inc", "sector": "Information Technology", "weight": 0.0468},
            {"symbol": "GOOG", "name": "Alphabet Inc Class C", "sector": "Communication Services", "weight": 0.0437},
            {"symbol": "META", "name": "Meta Platforms Inc", "sector": "Communication Services", "weight": 0.0423},
            {"symbol": "WMT", "name": "Walmart Inc", "sector": "Consumer Staples", "weight": 0.0402},
            {"symbol": "MU", "name": "Micron Technology Inc", "sector": "Information Technology", "weight": 0.0385},
            {"symbol": "TSLA", "name": "Tesla Inc", "sector": "Consumer Discretionary", "weight": 0.0365},
            {"symbol": "NFLX", "name": "Netflix Inc", "sector": "Communication Services", "weight": 0.0345},
            {"symbol": "COST", "name": "Costco Wholesale Corp", "sector": "Consumer Staples", "weight": 0.0325},
            {"symbol": "AMD", "name": "Advanced Micro Devices Inc", "sector": "Information Technology", "weight": 0.0310},
            {"symbol": "PEP", "name": "PepsiCo Inc", "sector": "Consumer Staples", "weight": 0.0280},
            {"symbol": "CSCO", "name": "Cisco Systems Inc", "sector": "Information Technology", "weight": 0.0265},
            {"symbol": "ADBE", "name": "Adobe Inc", "sector": "Information Technology", "weight": 0.0250},
            {"symbol": "TMUS", "name": "T-Mobile US Inc", "sector": "Communication Services", "weight": 0.0238},
            {"symbol": "INTU", "name": "Intuit Inc", "sector": "Information Technology", "weight": 0.0225},
            {"symbol": "QCOM", "name": "Qualcomm Inc", "sector": "Information Technology", "weight": 0.0218},
            {"symbol": "AMAT", "name": "Applied Materials Inc", "sector": "Information Technology", "weight": 0.0205},
            {"symbol": "TXN", "name": "Texas Instruments Inc", "sector": "Information Technology", "weight": 0.0195},
            {"symbol": "AMGN", "name": "Amgen Inc", "sector": "Health Care", "weight": 0.0185},
            {"symbol": "HON", "name": "Honeywell International Inc", "sector": "Industrials", "weight": 0.0175},
            {"symbol": "ISRG", "name": "Intuitive Surgical Inc", "sector": "Health Care", "weight": 0.0165},
            {"symbol": "BKNG", "name": "Booking Holdings Inc", "sector": "Consumer Discretionary", "weight": 0.0155},
            {"symbol": "PANW", "name": "Palo Alto Networks Inc", "sector": "Information Technology", "weight": 0.0145},
            {"symbol": "CMCSA", "name": "Comcast Corp", "sector": "Communication Services", "weight": 0.0135},
            {"symbol": "VRTX", "name": "Vertex Pharmaceuticals Inc", "sector": "Health Care", "weight": 0.0125},
            {"symbol": "SBUX", "name": "Starbucks Corp", "sector": "Consumer Discretionary", "weight": 0.0115},
            {"symbol": "GILD", "name": "Gilead Sciences Inc", "sector": "Health Care", "weight": 0.0105},
        ),
    ),
}


def get_index_definition(symbol: str) -> IndexDefinition:
    normalized = symbol.upper()
    if normalized not in INDEX_DEFINITIONS:
        raise KeyError(f"Unsupported index symbol: {symbol}")
    return INDEX_DEFINITIONS[normalized]


def supported_symbols() -> list[str]:
    return list(INDEX_DEFINITIONS)
